# This workflow is forked from:
# https://github.com/HypixelDatabase/HypixelTracking/blob/master/.github/workflows/discord.yml
name: Post apipolicy.json diff to Discord

on:
  workflow_run:
    workflows: ["Fetch API Policy"]
    types:
      - completed

jobs:
  post:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      parent_sha: ${{ steps.commit_info.outputs.parent_sha }}
    steps:
      - name: Checkout repository at the triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Determine change status, initial commit, and parent SHA
        id: commit_info
        run: |
          IS_CHANGED='false'
          IS_INITIAL='false'
          PARENT_SHA=''
          if git rev-parse --verify HEAD~ >/dev/null 2>&1; then
            PARENT_SHA=$(git rev-parse HEAD~)
            echo "Parent SHA: $PARENT_SHA"
            if git diff --quiet $PARENT_SHA HEAD -- apipolicy.json; then
              echo "apipolicy.json did not change compared to parent."
              IS_CHANGED='false'
            else
              echo "apipolicy.json changed compared to parent."
              IS_CHANGED='true'
            fi
            IS_INITIAL='false'
          else
            echo "Commit is the initial commit (no parent)."
            IS_INITIAL='true'
            if [ -f apipolicy.json ]; then
              echo "apipolicy.json exists in initial commit."
              IS_CHANGED='true'
            else
              echo "apipolicy.json does not exist in initial commit."
              IS_CHANGED='false'
            fi
          fi
          echo "is_changed=$IS_CHANGED" >> $GITHUB_OUTPUT
          echo "is_initial=$IS_INITIAL" >> $GITHUB_OUTPUT
          echo "parent_sha=$PARENT_SHA" >> $GITHUB_OUTPUT

      - name: Ping and Post GitHub Link
        if: steps.commit_info.outputs.is_changed == 'true'
        uses: ILikePlayingGames/discord-webhook@c533d6b0fda570a8fd1676878c05bc4f50cc1240
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: GitHub
          avatar-url: 'https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp'
          content: |
            <@&1362140322871640195> Policy Change Detected!
            ${{ format('[GitHub Link](<{0}/{1}/commit/{2}>)', github.server_url, github.repository, github.event.workflow_run.head_sha) }}

      - name: Get formatted diff for apipolicy.json (standard case)
        if: steps.commit_info.outputs.is_changed == 'true' && steps.commit_info.outputs.is_initial == 'false'
        id: get_diff
        uses: ILikePlayingGames/line-diff-action@v1.3
        with:
          commit-hash: ${{ steps.commit_info.outputs.parent_sha }}
          second-commit-hash: ${{ github.event.workflow_run.head_sha }}
          diff-algorithm: histogram
          delta-theme: discord

      - name: Get full file content for apipolicy.json (initial commit case)
        if: steps.commit_info.outputs.is_changed == 'true' && steps.commit_info.outputs.is_initial == 'true'
        run: |
          echo "Handling initial commit: outputting full file content to diff.txt."
          echo '```ansi' > diff.txt
          sed 's/^/+/' apipolicy.json >> diff.txt
          echo '```' >> diff.txt

      - name: Prepare diff content for Discord
        if: steps.commit_info.outputs.is_changed == 'true'
        run: |
          if [ -f diff.txt ]; then
            sed -i -e 's/`/\\`/g' diff.txt
            if [ "${{ steps.commit_info.outputs.is_initial }}" = "false" ]; then
               echo "Adding ANSI code block fences to diff.txt"
               sed -i -e '1i```ansi' -e '$a```' diff.txt
            fi
          else
            echo "diff.txt not found. Creating empty file."
            touch diff.txt
          fi

      - name: Count diff characters
        if: steps.commit_info.outputs.is_changed == 'true'
        run: |
          echo "DIFF_CHAR_COUNT=$(wc -c < diff.txt)" >> $GITHUB_ENV

      - name: Post diff/content as message to Discord
        if: steps.commit_info.outputs.is_changed == 'true' && env.DIFF_CHAR_COUNT <= 2000
        uses: ILikePlayingGames/discord-webhook@c533d6b0fda570a8fd1676878c05bc4f50cc1240
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: GitHub
          avatar-url: 'https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp'
          raw-content: diff.txt

      - name: Post diff/content as file to Discord
        if: steps.commit_info.outputs.is_changed == 'true' && env.DIFF_CHAR_COUNT > 2000
        uses: ILikePlayingGames/discord-webhook@c533d6b0fda570a8fd1676878c05bc4f50cc1240
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: GitHub
          avatar-url: 'https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp'
          filename: diff.txt
