# This workflow is forked from:
# https://github.com/HypixelDatabase/HypixelTracking/blob/master/.github/workflows/discord.yml
name: Post apipolicy.json diff to Discord
on:
  push:
    paths:
      - 'apipolicy.json' # <-- Only run if this file changes
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch HEAD and the commit before it
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Ping and Post GitHub Link
        uses: ILikePlayingGames/discord-webhook@c533d6b0fda570a8fd1676878c05bc4f50cc1240
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: GitHub
          avatar-url: 'https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp'
          content: |
            <@&1362140322871640195> Policy Change Detected!
            ${{ format('[GitHub Link](<{0}/{1}/commit/{2}>)', github.server_url, github.repository, github.sha) }}
      - name: Get formatted diff for apipolicy.json
        id: get_diff
        uses: ILikePlayingGames/line-diff-action@v1.3
        with:
          commit-hash: '@~'
          diff-algorithm: histogram
          delta-theme: discord
      - name: Wrap diff in code block
        run: >-
          sed -i -e 's/`/\\`/g' -e '1i```ansi' -e '$a```\n' diff.txt
      - name: Count diff characters
        run: >-
          echo "DIFF_CHAR_COUNT=$(wc -c < diff.txt)" >> $GITHUB_ENV
      - name: Post as message to Discord
        if: ${{ env.DIFF_CHAR_COUNT <= 2000 }}
        uses: ILikePlayingGames/discord-webhook@c533d6b0fda570a8fd1676878c05bc4f50cc1240
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: GitHub
          avatar-url: 'https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp'
          raw-content: diff.txt
      - name: Post as file to Discord
        if: ${{ env.DIFF_CHAR_COUNT > 2000 }}
        uses: ILikePlayingGames/discord-webhook@c533d6b0fda570a8fd1676878c05bc4f50cc1240
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: GitHub
          avatar-url: 'https://cdn.discordapp.com/avatars/999680196040982618/df91181b3f1cf0ef1592fbe18e0962d7.webp'
          filename: diff.txt
