name: Fetch API Policy

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch API policy data
        run: curl -sSL https://api.ragingenby.dev/apipolicy | jq '.' > apipolicy.json

      - name: Check for changes
        id: check_changes
        run: |
          if [ ! -f apipolicy.json ]; then
            echo "apipolicy.json not found after fetch."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          if git diff --quiet apipolicy.json; then
            echo "No changes detected in apipolicy.json."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "File changed, proceeding to commit."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "RagingEnby"
          git config user.email "ragingenby@users.noreply.github.com"

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git add apipolicy.json
          git commit -m "Update apipolicy.json from API"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

      - name: Trigger repository dispatch to post diff to Discord
        if: steps.check_changes.outputs.changed == 'true'
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${PAT}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "apipolicy-pushed"}'
